# Generated by Django 5.2.3 on 2025-06-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desaparecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo da pessoa desaparecida.', max_length=255)),
                ('idade', models.PositiveIntegerField(blank=True, help_text='Idade da pessoa no momento do desaparecimento.', null=True)),
                ('data_desaparecimento', models.DateField(blank=True, help_text='Data em que a pessoa desapareceu.', null=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição física, roupas que usava, e outras características relevantes.')),
                ('ultima_localizacao', models.CharField(blank=True, help_text='Último local conhecido onde a pessoa foi vista.', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bo_numero', models.CharField(help_text='Número do Boletim de Ocorrência', max_length=50, unique=True)),
                ('data_registro', models.DateField(auto_now_add=True, help_text='Data de registro do caso.')),
                ('status', models.CharField(choices=[('desaparecido', 'Desaparecido'), ('encontrado', 'Encontrado'), ('em_investigacao', 'Em Investigação')], default='desaparecido', help_text='Status atual do caso.', max_length=20)),
                ('foto_principal', models.ImageField(blank=True, help_text='Foto principal da pessoa desaparecida.', null=True, upload_to='fotos_desaparecidos/')),
                ('foto_progressao', models.ImageField(blank=True, help_text='Foto de progressão de idade, se aplicável.', null=True, upload_to='fotos_desaparecidos/')),
            ],
        ),
    ]
