# Generated by Django 5.2.1 on 2025-06-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desaparecidos_app", "0002_alter_desaparecido_bo_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desaparecido",
            name="bo_numero",
            field=models.CharField(
                help_text="Número do Boletim de Ocorrência", max_length=50, unique=True
            ),
        ),
    ]
