# Generated by Django 5.2.1 on 2025-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desaparecidos_app", "0003_alter_desaparecido_bo_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desaparecido",
            name="foto_principal",
            field=models.ImageField(
                blank=True,
                help_text="Foto principal da pessoa desaparecida.",
                null=True,
                upload_to="media/fotos_desaparecidos/",
            ),
        ),
        migrations.AlterField(
            model_name="desaparecido",
            name="foto_progressao",
            field=models.ImageField(
                blank=True,
                help_text="Foto de progressão de idade, se aplicável.",
                null=True,
                upload_to="media/fotos_desaparecidos/",
            ),
        ),
    ]
