# Generated by Django 5.2.1 on 2025-06-01 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desaparecidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="desaparecido",
            name="data_registro",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Data de registro do caso.",
            ),
            preserve_default=False,
        ),
    ]
