# Generated by Django 5.2.1 on 2025-06-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desaparecidos", "0002_desaparecido_data_registro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desaparecido",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="desaparecido",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
