# Generated by Django 5.2.1 on 2025-06-02 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desaparecidos", "0003_alter_desaparecido_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoLocalizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_avistamento",
                    models.DateTimeField(
                        help_text="Data e hora em que a pessoa foi vista ou a localização foi registrada."
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "descricao_local",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do local ou circunstância do avistamento/registro.",
                        null=True,
                    ),
                ),
                ("data_registro_historico", models.DateTimeField(auto_now_add=True)),
                (
                    "desaparecido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_localizacoes",
                        to="desaparecidos.desaparecido",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_avistamento"],
            },
        ),
    ]
